[pytest]

addopts = -vs --alluredir=allure-results --clean-alluredir

# 测试用例命名规则（显式声明，避免歧义）
python_files = test_*.py
python_classes = Test*
python_functions = test_*

log_cli = true
log_cli_level = INFO
log_cli_format = %(asctime)s [%(levelname)s] %(filename)s:%(lineno)d - %(message)s
log_cli_date_format = %Y-%m-%d %H:%M:%S



